### ISSUE TITLE
Improvements to Geo-related schemas (e.g. GeoShape) liase with GeoJSON(-LD), W3C GeoSpatialWG et al.

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#113]
http://schema.org/GeoShape
http://schema.org/box
http://schema.org/polygon

See discussion at https://github.com/geojson/geojson-ld/issues/28

Original text: "See http://geowanking.org/pipermail/geowanking_geowanking.org/2012-June/026179.html
Schema.org's design came via rNews from GeoRSS, and there from GML. It needs a fresh look."

This is now a meta bug for improvements to schema.org's geo(spatial) vocabulary:

Geospatial 'core' terms:

* [ ] ~~http://schema.org/latitude http://schema.org/longitude http://schema.org/elevation on http://schema.org/GeoCoordinates are vague; they don't mention e.g. wgs-84.~~ #802
* [ ] http://schema.org/elevation has no units or base; contrast e.g. W3C basic geo which we defined (eventually) as "The WGS84 altitude of a SpatialThing (decimal meters  above the local reference ellipsoid)."
* [x] http://schema.org/box ~~has the wrong text (copy/paste error), definition is identical to http://schema.org/polygon. Needs a definition.~~ https://github.com/schemaorg/schemaorg/issues/8
* [ ] Suggest to also allow http://schema.org/geo on Organization (however it is on Place and therefore applicable on any LocalBusiness already)
* [x] GeoShape and GeoCoordinates should allow a postalCode for rough positioning.
* [ ] a GeoCircle would improve upon existing simple 'circle' property of GeoShape, as publishers could define radius and (various approaches to) centre without pushing it all into textual micro-syntax.

Related schema.org vocabulary for locally oriented info:

* [ ] Physical Web e.g. via beacons such as https://github.com/google/physical-web - what kind of richer schemas are needed to support these use cases?
* [ ] Accessibility of Places - schema.org expects to do some work to support scenarios such as 'is there a wheelchair ramp?', see https://github.com/schemaorg/schemaorg/issues/254
* [ ] Opening Hours markup needs improving - https://github.com/schemaorg/schemaorg/issues/245

**Comment by danbri** [comment]
I've added a simple mechanism (a GeoCircle + geoRadius, geoMidpoint) for circular geoshapes after hearing 4 years of feedback that 'circle' is baffling and hard to use. We could do likewise for polygons, boxes etc but radius-based circle is pretty simple. There's a question of whether miles, kilometres or metres would be the best default - any views?

**Comment by danbri** [comment]
Answering my own question, I've added a range of Distance (schema.org's syntax that allows '5 km' etc.) and noted that it can be used; when it isn't, we default to metres.

**Comment by mfhepp** [comment]
Note that my hotel proposal also has a mechanism for indicating links between places with distance information, see

http://sdo-hotels.appspot.com/distanceInformation
and
http://sdo-hotels.appspot.com/DistanceSpecification

This allows stating that e.g. a hotel is 5 km from a particular airport or the city center or a touristic spot etc.

**Comment by neothemachine** [comment]
I just tried to use
```html
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Dataset",
  "url": "http://www.example.com",
  "spatial": {
    "geo": {
      "box": "50 4 52 6"
    }
  }
}
</script>
```
on the [testing tool](https://developers.google.com/structured-data/testing-tool/) but it complains about the box. Is the tool not up to date or is my json wrong?

**Comment by vholland** [comment]
Google's testing tool sometimes gets confused if type declarations are omitted. 

The following shows no errors:

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Dataset",
  "url": "http://www.example.com",
  "spatial": {
    "geo": {
      "@type": "GeoShape",
      "box": "50 4 52 6"
    }
  }
}
</script>
```

**Comment by danbri** [comment]
Fixed in http://schema.org/docs/releases.html#v2.2  - thanks all
