### ISSUE TITLE
Show how to use Wikidata terms, "schema.org"-style, particularly in JSON-LD

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1186]
This builds on earlier exploration in #280 (mappings). Mappings will be needed. @vrandezo + @danbri collaboration notes live here now.

Goal: we want to be able to write JSON-LD (or RDFa/Microdata) that draws upon Wikidata content. Specifically, properties, types and identified entities. This could be standalone markup or mixed in with schema.org and other vocabularies.
- _Properties_: Wikidata has first class / built-in support for properties (these get P-identifiers e.g. see https://www.wikidata.org/wiki/Property:P1082 for 'population').
- _Types_: These exist somewhat implicitly in Wikidata content but less so in the infrastructure (like hashtags and RTs in early Twitter). Types show up with P31 (instanceOf) and P279 (subClassOf) in Wikidata; these correspond roughly to rdf:type and rdfs:subClassOf in RDF (RDFa/JSON). For example https://www.wikidata.org/wiki/Q128207 (Earth) is instanceOf (P31) https://www.wikidata.org/wiki/Q128207 (Terrestrial Planet)
- _Entities_: For example, https://www.wikidata.org/wiki/Q42 (Douglas Adams) is instanceOf  https://www.wikidata.org/wiki/Q5 (Human). We should show how to use Wikidata unique identifiers for well known entities within schema.org-style markup, e.g. using schema.org sameAs (see #1162).

Ideally we would like to exploit mappings so that Wikidata terminology can be mixed in with common schema.org terms like Person, Place, Event etc., supplying properties when schema.org and its other extensions have nothing. 

Subtasks:
- [ ] collect mappings where possible #280 (optional but very useful)
- [x] for each Wikidata property, we need to know if it is a string-valued vs thing-valued property i.e. whether or not the datatype of the property is pointing to an item. This distinction is needed in JSON-LD @context definitions and used in parsing JSON-LD to determine how to treat textual values e.g. whether "../news/" gets expanded to a full URL.
- [ ] Optionally (but useful for discovery / overview) it would be good to have a view of Wikidata in more RDF-ish (schema.org-ish) terms. Specifically as a hierarchy of types, properties and their associations.
  - [x] @mkroetzsch  has apparently done this (Denny will dig links)
  - [x] Note that Wikidata is even weaker than schema.org in terms of type/property associations; these need to be mined from instance data e.g. via query.wikidata.org
- [x] Generate a JSON-LD context file that can be used in JSON-LD parsing
- [x] Write JSON-LD examples showing 
  - [x] JSON-LD properties from Wikidata mixed into schema.org
- [ ] Generate at least single page HTML overview / report of the terms.

This assumes that we are treating Wikidata as a schema.org "[external extension](schema.org/docs/extension.html)". If instead we handled it as an hosted extension we would need to ensure no type or property names clashed with existing usage. This is infeasible unless we used Q-nnn and P-nnn identifiers, which are not very usable.

The actual final markup ought to allow for ugly but permanent IDs to be used, but also for the (current and former) human readable labels e.g. "population" to be used in markup. A larger, later problem is how these are documented and discovered but we assume existing tools could be adapted, and that data consumers will give examples that interest them. 
# Worked example

Usecase. The [Finder-Spyder](https://en.wikipedia.org/wiki/Finder-Spyder) wants to use schema.org people descriptions, but needs a blood type property. At this time schema.org doesn't have such a property. One option would be to propose this as a schema.org addition or extension and wait for it to be added to schema.org's Pending extension or fully ratified. However, Wikidata already has such a property: https://www.wikidata.org/wiki/Property:P1853 

We want to show how Wikidata's "blood type" property can be used in markup.
# Things to remember

Property names within Wikidata are constrained to be unique (per language); types are not.

**Comment by danbri** [comment]
Variations for discussion.

Note that the URL http://wikidatavocab.example.org would need to serve up a
JSON-LD context file that defines each property. See schema.org's
for comparison, available via http://schema.org/docs/jsonldcontext.json

Until we publish such a context file, full JSON-LD parsers including
http://json-ld.org/playground/ will not work unless the context declarations are
given inline. Therefore from Variant 2 onwards we do this, making the examples
verbose but self-contained.

Wikidata gives us Q19831450 human blood type, Q19831453 for the type A, and
P1853 for the property relating people (or animals) to blood types. Initially
we write the facts out in full; later we might consider simple shortcuts.


Variant 1:

    <script type="application/ld+json">
    {
    "@context":  ["http://schema.org/", "http://wikidatavocab.example.org"],
      "@type": "Person",
      "name": "Dan Brickley",
      "wd_blood_type": {
         "@type": "wd_Human_blood_type",
         "@id": "https://www.wikidata.org/entity/Q19831453",
         "name": "A"
      }
     }
    </script>

Variant 2:

    <script type="application/ld+json">
    {
     "@context": {
      "@vocab": "http://schema.org/",
      "wd_blood_type": {"@id": "https://www.wikidata.org/entity/P1853", "@type": "@id" }
     },
     "@type": "Person",
      "name": "Dan Brickley",
      "wd_blood_type": {
         "@id": "https://www.wikidata.org/entity/Q19831453",
         "name": "A"
      }
     }
    </script>

Note: We choose not to give a type to the "A" entity explicitly here, although it could be done.

**Comment by vrandezo** [comment]
Here's an example of the properties that @mkroetzsch calculated for a Wikidata-item which is used as a type:
http://tools.wmflabs.org/sqid/#/view?id=Q5 (see the field "properties for this type")

Note that this is not about the domain of the property, but rather which properties are typically used for a given type.

**Comment by danbri** [comment]
I find the blood type example reasonably compelling but rather clunky as it is a rather simple fact and it seems many would likely want a text-valued property. Can we find other text valued properties that make for more persuasive examples?

**Comment by vrandezo** [comment]
SQID can be used to browse through the Wikidata vocabulary:

http://tools.wmflabs.org/sqid/#/browse?type=properties

To find properties with a string datatype, the filters at the right hand side can be used.

**Comment by danbri** [comment]
Variants 4 and 5
================

Let's lose the wd_ prefix, but explain what we're doing. These examples do not use
inline context but instead import schema.org and the wikidata vocabularies. The order
of the array matters. Note that Google's Structured Data Testing Tool does not at the 
time of writing handle array-valued context declarations properly.

We assume the wikidata context declares the property much as before, i.e.:

>   "blood_type": {"@id": "https://www.wikidata.org/entity/P1853", "@type": "@id" }

Variant 4 - wikidatavocab overlaid on top of schema.org
==========

In this example, if schema.org has, or later adds, a "blood_type" property it will
be over-ridden by the blood_type that we are here using from Wikidata.

    <script type="application/ld+json">
    {
    "@context":  ["http://schema.org/", "http://wikidatavocab.example.org"],
     "@type": "Person",
      "name": "Dan Brickley",
      "blood_type": {
         "@id": "https://www.wikidata.org/entity/Q19831453",
         "name": "A"
      }
     }
    </script>

Variant 5
=========

In this example, schema.org is overlaid on top of the Wikidata vocabulary. We 
assume that initially it has no properties whose name is exactly "blood_type".
In future if such were added, a context-using compliant JSON-LD parser would 
generate http://schema.org/blood_type instead of https://www.wikidata.org/entity/P1853
for the property name.

Aside: schema.org currently has no properties with '_' in the property ID.

    <script type="application/ld+json">
    {
    "@context":  ["http://wikidatavocab.example.org", "http://schema.org/"],
     "@type": "Person",
      "name": "Dan Brickley",
      "blood_type": {
         "@id": "https://www.wikidata.org/entity/Q19831453",
         "name": "A"
      }
     }
    </script>

**Comment by danbri** [comment]
Variant 6
=======

Prettying it up. We return to using inline contexts for demo purposes. We remove the 'wd_' on
assumption that we can live with the over-ride rules shown above (in 4+5).

Here we are saying that the value of blood_type is an item whose name is "A".

{
 "@context": {
  "@vocab": "http://schema.org/",
  "blood_type": {"@id": "https://www.wikidata.org/entity/P1853", "@type": "@id" }
 },
 "@type": "Person",
  "name": "Dan Brickley",
  "blood_type": { "name": "A"  }
 }

Parsed JSON-LD triples:

* _:b0 <http://schema.org/name> "Dan Brickley" .
* _:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person> .
* _:b0 <https://www.wikidata.org/entity/P1853> _:b1 .
* _:b1 <http://schema.org/name> "A" .

Variant 7 - bad

This is bad because blood_type's wikidata property is item-valued so "A" will be handled
as a relative URI reference, e.g. http://mysite.geocities.example.com/awesome.php?cookie1234=wefewer#A".

This is not what we want.

{
 "@context": {
  "@vocab": "http://schema.org/",
  "blood_type": {"@id": "https://www.wikidata.org/entity/P1853", "@type": "@id" }
 },
 "@type": "Person",
  "name": "Dan Brickley",
  "blood_type": "A"
 }


Variant 8 - better?

But not much better than 6.

{
 "@context": {
  "@vocab": "http://schema.org/",
  "blood_type": {"@id": "https://www.wikidata.org/entity/P1853", "@type": "@id" }
 },
 "@type": "Person",
  "name": "Dan Brickley",
  "blood_type": { "@value": "A" }
 }

 Parsed JSON-LD triples:

* _:b0 <http://schema.org/name> "Dan Brickley" .
* _:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person> .
* _:b0 <https://www.wikidata.org/entity/P1853> "A" .

**Comment by danbri** [comment]
@vrandezo and I have been prospecting for "interesting properties" that could play well alongside existing schema.org terms, adding detail/depth. He'll post most of these but here are some from the  lifesciences /cc @natashafn.


* http://tools.wmflabs.org/sqid/#/view?id=P644 genomic start
* http://tools.wmflabs.org/sqid/#/view?id=P645 genomic end
* http://tools.wmflabs.org/sqid/#/view?id=P637 RefSeq protein ID
* http://tools.wmflabs.org/sqid/#/view?id=P639 RefSeq RNA ID (etc.)

see https://www.wikidata.org/wiki/Wikidata:List_of_properties/Natural_science for more.

**Comment by vrandezo** [comment]
A few example properties with non-item datatype:
* full text available at (http://www.wikidata.org/wiki/Property:P953)
* chemical formula (http://www.wikidata.org/wiki/Property:P274)
* licence plate code (http://www.wikidata.org/wiki/Property:P395)
* number of children (http://www.wikidata.org/wiki/Property:P1971)
* Elo rating (http://www.wikidata.org/wiki/Property:P1087)
* employees (http://www.wikidata.org/wiki/Property:P1128)
* Erdős number (http://www.wikidata.org/wiki/Property:P2021)
* number of participants (http://www.wikidata.org/wiki/Property:P1132)
* visitors per year (http://www.wikidata.org/wiki/Property:P1174)
* number of speakers (http://www.wikidata.org/wiki/Property:P1098)
* floors above ground (http://www.wikidata.org/wiki/Property:P1101)
* frequency (http://www.wikidata.org/wiki/Property:P2144)
* beats per minute (http://www.wikidata.org/wiki/Property:P1725)
* students count (http://www.wikidata.org/wiki/Property:P2196)
* motto text (http://www.wikidata.org/wiki/Property:P1451)
* first line (http://www.wikidata.org/wiki/Property:P1922)

**Comment by vrandezo** [comment]
Example for my Erdos number:

{
  "@context": {
  "@vocab": "http://schema.org/",
  "erdos_number": {"@id": "https://www.wikidata.org/entity/P2021" }
},
  "@type": "Person",
  "name": "Denny Vrandečić",
  "erdos_number": "4"
}

**Comment by vrandezo** [comment]
SPARQL query to get all properties and their types from Wikidata:

  SELECT ?prop ?type WHERE {
    ?prop a wikibase:Property .
    ?prop wikibase:propertyType ?type .
  }
  LIMIT 10

Link to query service: http://tinyurl.com/gtmfdme

**Comment by jvandriel** [comment]
How about using ```"additionalProperty":"PropertyValue"``` for this like such:

```<script type="application/ld+json">
{
"@context": "http://schema.org/",
"@type": "Person",
"name": "Dan Brickley",
"additionalProperty": 
{
  "@type": "PropertyValue",
  "@id": "",
  "name": "blood_type",
  "value": "A"
}
</script>```

If it's valid that would imply this can be expressed in microdata as well:

```<div itemscope itemtype="http://schema.org/Person">
  <span itemprop="name">Dan Brickley</span><br>
  <span itemprop="additionalProperty" itemscope itemtype="PropertyValue" itemid="https://www.wikidata.org/entity/P1853">
    <meta itemprop="value" content="blood_type">blood type: <span itemprop="value">A</span>
  </span>
</div>```

**Comment by danbri** [comment]
@jvandriel yes, that would be one way to give more structure to PropertyValue markup. However here we are looking for something that gives a less indirect structure.

**Comment by danbri** [comment]
Here is a first cut at a JSON-LD context definition for Wikidata properties. I'll share the horrible code later.

http://wdvoc-1323.appspot.com/

**Comment by danbri** [comment]
I had expected this to work:

    {
      "@context": [ "http://schema.org/", "http://wdvoc-1323.appspot.com/" ],
      "@type": "Person",
      "name": "Denny Vrandečić",
      "erdos_number": "4"
    }

... in http://json-ld.org/playground/ (but not at Google SDTT). Unfortunately something isn't yet right, I get "Dereferencing a URL did not result in a valid JSON-LD object.". Maybe I need to set the HTTP media type? /cc @lanthaler

**Comment by gkellogg** [comment]
Running it at http://rdf.greggkellogg.net/distiller, I get the following Turtle:

```turtle
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

 [
     a schema:Person;
     <http://wdvoc-1323.appspot.com/voc/erdos_number> "4";
     <http://wdvoc-1323.appspot.com/voc/name> "Denny Vrandečić"
 ] .
```

However, CURL indicates you're not setting CORS headers, which may be the problem with the playground. The error message does say something about CORS, but it's not obvious.

```
HTTP/1.1 200 OK
Date: Fri, 27 May 2016 01:28:42 GMT
Expires: Fri, 27 May 2016 01:38:42 GMT
ETag: "8Bmfjw"
Content-Type: application/ld+json
Server: Google Frontend
Cache-Control: public, max-age=600
Content-Length: 186365
Age: 176
```

**Comment by danbri** [comment]
Got it, i think. Need to add CORS headers. In appengine app.yaml this ought to be:

http_headers:
    Access-Control-Allow-Origin: "*"

Will test it asap.

**Comment by danbri** [comment]
Ah i see @gkellogg's comment now. CORS it is, then! Thanks!

**Comment by danbri** [comment]
Ok that fixed it! Here is the original usecase working with this context URL.

Variant 9 (as variant 6 but with a functioning remote context file)
=======

    {
      "@context": [ "http://schema.org/", "http://wdvoc-1323.appspot.com/" ],
      "@type": "Person",
       "name": "Dan Brickley",
       "blood_type": { "@value": "A" }
    }

**Comment by danbri** [comment]
Ah, we had a bug in the examples or a weakness in the generated JSON-LD: 

    {
      "@context": [ "http://schema.org/", "http://wdvoc-1323.appspot.com/" ],
      "@type": "Person",
      "name": "Denny Vrandečić",
      "Erdős_number": "4"
    }

... is needed. Current context file doesn't work with "erdos_number". It is an open question how flexible we would want to be in generating one or more human friendly property aliases, whether to downcase capitals, simplify non-ascii chars etc.

**Comment by mfhepp** [comment]
When designing examples (and maybe the JSON-LD context, not sure) for this, could you please try to allow / recommend the use of the following types as the range for ALL properties from Wikidata?

- http://schema.org/QuantitativeValue
- http://schema.org/PropertyValue
- http://schema.org/QualitativeValue

It will help being able to reuse properties from Wikidata with more granular markup, in particular for point values and ranges (like unit codes, value references, etc.).

Martin

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by mfhepp** [comment]
Here is an example showing how to use the property "track gauge", 

    "https://www.wikidata.org/wiki/Property:P1064" 

with a German diesel locomotive:


{
  "@context": [ "http://schema.org/", "http://wdvoc-1323.appspot.com/" ],
  "@type": "Vehicle",
  "name": "DB Class 218",
  "description" : "The DB Class 218 (before 1968 the DB Class V 164) are a class of 4 axle, diesel hydraulic locomotives acquired by the Deutsche Bundesbahn for use on main and secondary lines for both passenger and freight trains."
  "track_gauge" : { 
            "@type" : "QuantitativeValue",
            "value" : "1435",
            "unitCode" : "MMT"}
}


-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by lanthaler** [comment]
@danbri, see you already found the problem. I was wondering what result you expected. For instance, did you want `name` to be mapped to WikiData or Schema.org?

**Comment by danbri** [comment]
Thanks.

Markus - right now just exploring designs. Schema.org name would be more widely understood.

Martin - thanks for the example. Currently this is effectively schemaless; properties don't expect specific types so your example works.

**Comment by danbri** [comment]
@lydiapintscher - do you have a sense for whether the JSON-LD context prototyped here is something that you'd want to host on a Wikidata.org domain somewhere?

**Comment by lydiapintscher** [comment]
I don't have enough understanding of it to say yet. Denny: Quick chat about it?

**Comment by danbri** [comment]
@lydiapintscher here's a bit more of an explanation (copy/pasted from an email)

This is a rough demo of Wikidata as a structured data vocabulary. 

In particular it targets JSON-LD and schema.org, with the
intent that any properties in use at Wikidata should also be something
webmasters/publishers can stick into schema.org descriptions elsewhere
in the Web. It is also an exploration of the kinds of thing schema.org will need
to do around JSON-LD for other 3rd party external extensions such as
http://gs1.org/voc/ from GS1 ("cheeseFirmness" etc.).

http://wdvoc-1323.appspot.com/ is a first cut at a generated JSON-LD
context. If you're not used to JSON-LD contexts, they basically
provide additional definitions on top of RDFS that allow JSON-LD
syntax to be simple. Most importantly they classify properties as
defaulting to string values vs thing values. I didn't set up content
negotiation or attempt a pretty HTML UI. Also we didn't look very
deeply at types, or at mappings.

https://github.com/schemaorg/schemaorg/issues/1186 walks through a few
variations on the idea.

{
  "@context": [ "http://schema.org/", "http://wdvoc-1323.appspot.com/" ],
  "@type": "Person",
   "name": "Dan Brickley",
   "blood_type": { "@value": "A" }
}

... is an example of an entity-valued property (aliased as blood_type); while

{
  "@context": [ "http://schema.org/", "http://wdvoc-1323.appspot.com/" ],
  "@type": "Person",
  "name": "Denny Vrandečić",
  "Erdős_number": "4"
}

... shows a literal-valued property, aliased as "Erdős_number" (and
potentially also dumbed down to "erdos_number"...). Since schema.org
has neither blood_type or erdos_number this seems a relatively
painless way of giving us a new properties for free (+ piggybacking on
Wikidata's social/technical machinery for defining them).

In both cases, a compliant JSON-LD parser will fetch the context file
and if the property is spelled in a way that matches an entry in the
context file, it'll map such that generated triples use the official
P-number property URIs from Wikidata.

So http://json-ld.org/playground/ generates the following triples:

_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
<http://schema.org/Person> .
_:b0 <http://www.wikidata.org/entity/P1853> "A" .
_:b0 <http://www.wikidata.org/entity/P2561> "Dan Brickley" .

and

_:b0 <http://www.wikidata.org/entity/P2021> "4" .
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
<http://schema.org/Person> .
_:b0 <http://www.wikidata.org/entity/P2561> "Denny Vrandečić" .

You should get the same triples from
http://rdf.greggkellogg.net/distiller but Google SDTT will not yet
understand this. Partly because we don't handle arbitrary (or even
selected) extension context files, and partly because we can't handle
an array as value of @context.

One interesting thing about JSON-LD here is that it differs from
earlier RDF syntaxes by allowing vocabulary mixing into a seemingly
flat namespace.

Consider

{
  "@context": [ "http://schema.org/", "http://wdvoc-1323.appspot.com/" ],
  "@type": "Person",
  "name": "Denny Vrandečić",
  "Erdős_number": "4"
}

vs

{
  "@context": [ "http://wdvoc-1323.appspot.com/" , "http://schema.org/" ],
  "@type": "Person",
  "name": "Denny Vrandečić",
  "Erdős_number": "4"
}

Since both schema.org and the demo wdvoc context files declare a
property called "name", the order of the @context array matters. The
first example will emit

_:b0 <http://www.wikidata.org/entity/P2561> "Denny Vrandečić" .

while the 2nd will emit:

_:b0 <http://schema.org/name> "Denny Vrandečić" .

... basically the last entry in the array gets the "last word" and
overrides earlier property definitions.

**Comment by danbri** [comment]
See https://github.com/schemaorg/schemaorg/issues/1094#issuecomment-237627353 for an example of JSON-LD's ability to map simple strings to URIs within property values, via @context declarations. I believe we could use these for types by adding all the type shortname/URI pairs to the ever-growing context file.

**Comment by pigsonthewing** [comment]
Property names in Wikidata are indeed constrained to be unique; but they are not guaranteed to be persistent. for instance, "population"  (P1082) could be changed to "number of people" and "human" (Q5) could be changed to "person". And uniqueness is only guaranteed within the language.  A _different_ property could have the French label "person".

Always use "P" and "Q" identifiers.

**Comment by danbri** [comment]
@pigsonthewing yes, though even the P and Q identified terms could have various flavours of semantic drift as their meaning gets clarified through use. The technique here should also work with the machine IDs though I expect many publishers could want to gamble on using the more human-friendly variant. If they published their own wdvoc-1323.appspot.com they could insulate themselves from changes. Or a commonly maintained wdvoc-1323.appspot.com could add _2 _3 suffixes for properties whose ID changed. Right now I'm only exploring the options...

**Comment by danbri** [comment]
@pigsonthewing 14 months later, https://www.wikidata.org/wiki/Property:P1082 is still "population". Does anyone have metrics on property name volatility?

The basic idea of using Wikidata as vocabulary in markup can work with either P/Q numbers or their natural language labels (not necessarily English). If the latter the indirection needs to be documented in a context file, which isn't necessarily changed when Wikidata evolves.

**Comment by pigsonthewing** [comment]
> Does anyone have metrics on property name volatility?

Interesting question; not that I know of.

**Comment by Tpt** [comment]
@danbri Are you talking about http://wikiworkshop.org/2018/papers/wikiworkshop2018_paper_10.pdf ?

**Comment by danbri** [comment]
@Tpt I think all I saw was a Twitter comment, but maybe inspired by this (very nice :) work...

**Comment by danbri** [comment]
This was a useful investigation but I see no obvious next step here, closing it for now.
