### ISSUE TITLE
properly relate Product and Service (ProductOrService)

### ISSUE THREAD

**Issue by elf-pavlik** [schemaorg/schemaorg#134]
http://schema.org/Product
http://schema.org/Service

from reply on public-vocabs thread _http://lists.w3.org/Archives/Public/public-vocabs/2014Sep/0229.html_ by @mfhepp

> I suppose that "Service" was once added for some specific, but maybe only hypothetical use-case by one of the sponsors of schema.org.
> 
> In order to keep the vocabulary clean, however, I suggest to use Product (in the sense of ProductOrService) as long as the distinction between product and service does not really matter for processing the data. Many "products" are nowadays bundles of tangible objects and services anyway, so unless you need specific properties that do not make sense for schema:Product, I would minimize the use of schema:Service.
> 
> Note: In principle, we could make Service a subclass of Product, and/or include a superclass ProductOrService (which was the original name in GoodRelations anyway):
> 
> schema:ProductOrService
>     -> schema:Product
>         -> schema:SomeProducts
>         -> schema:IndividualProduct
>         -> schema:ProductModel
>     -> schema:Service
> 
> This has two caveats, though: First, the more special types SomeProducts, IndividualProduct, and ProductModel are then not available for services any longer. But on the contrary, the notion of individuals, models, and bags of products does not really fit to pure services anyway (or they do not matter that much). So this seems acceptable to me.
> 
> Second, if we want to add specializations for very important types of products and services (like Vehicle/Car; HotelRoom, etc.), we will have to make a strict decision on whether that type is a product or a service. That can lead to inconsistency in the vocabulary over time. For instance, I think that "Taxi" should be better placed beneath schema:Product etc. For me, this is the reason for rather sticking to the "ProductOrService" notion of schema:Product.
### TODO
- [ ] http://schema.org/Product
- [ ] http://schema.org/Service
- [ ] http://schema.org/BroadcastService

**Comment by danbri** [comment]
I see a lot of discussion here. Would any of you care to summarize where you think we are on this issue?

**Comment by elf-pavlik** [comment]
@danbri to lower confusion we can start with adding short notes to Service and Product [as you suggested](http://lists.w3.org/Archives/Public/public-vocabs/2014Sep/0273.html)

>A service provided by an organization, e.g. delivery service,
print services, etc. (Note that a particular delivery or print job can
be modeled as a Product.)

I would suggest adding something matching it to Product

"Any offered product or service. For example: a pair of shoes; a concert ticket; the rental of a car; a haircut; or an episode of a TV show streamed online. (Note that Service in schema.org represents general type of services. Please use Product for particular occurrences of such services, for example used in market transaction)" 

@mfhepp at some point will produce more in depth explanations to include among others on http://schema.org/docs/documents.html

**Comment by elf-pavlik** [comment]
@mfhepp how do we model *[Offer](http://schema.org/Offer)*/*[Demand](http://schema.org/Demand)* for *[Action](http://schema.org/Action)*/*Activity* like:
* [TravelAction](http://schema.org/TravelAction)
 * [BusTrip](http://schema.org/BusTrip)
 * [TrainTrip](http://schema.org/TrainTrip)
 * [Flight](http://schema.org/Flight)
 * [Taxi](https://schema.org/Taxi)
* [ConsumeAction](http://schema.org/ConsumeAction)
 * [EatAction](http://schema.org/EatAction) (e.g. an apple)
 * [DrinkAction](http://schema.org/DrinkAction) (e.g. cup of coffee)
 * [UseAction](http://schema.org/UseAction) (e.g. bike from bikesharing pool)
* [CreateAction](http://schema.org/CreateAction)
 * [CookAction](http://schema.org/CookAction)
 * [TranslateAction](http://schema.org/TranslateAction)
 * [PhotographAction](http://schema.org/PhotographAction)
 * [FilmAction](http://schema.org/FilmAction)

I also understand that we sometimes also introduce *[Ticket](http://schema.org/Ticket)* but i ask for an Activity and not ticket for this Activity! IMO *[Ticket](http://schema.org/Ticket)* serves more in a way of *[Recipt](http://schema.org/Receipt)* minted with *[PriceSpecification](https://schema.org/PriceSpecification)*  ([DataShape](http://www.w3.org/2014/data-shapes)?) which one can use to *ClaimAccess* / *[PayAction](http://schema.org/PayAction)*

* [FoodEvent](https://schema.org/FoodEvent) -- [EatAction](https://schema.org/EatAction) & [DrinkAction](https://schema.org/DrinkAction)

* [MusicEvent](https://schema.org/MusicEvent) -- [ListenAction](https://schema.org/ListenAction)

* [TheaterEvent](https://schema.org/TheaterEvent) -- [WatchAction](https://schema.org/WatchAction)

* [SportsEvent](https://schema.org/SportsEvent) -- [WatchAction](http://schema.org/WatchAction) but also [ExerciseAction](https://schema.org/ExerciseAction) (e.g. Yoga Class)

* [EducationEvent](https://schema.org/EducationEvent) -- [LearnAction](https://schema.org/LearnAction) (sub: ConsumeAction) & [TeachAction](https://schema.org/TeachAction) (sub: CreateAction)

* [DanceEvent](https://schema.org/DanceEvent) -- [DanceAction](https://schema.org/DanceAction)

**Comment by elf-pavlik** [comment]
Possibly also worth track Web Payments IG work, they just published FPWD of Use Cases which includes e.g. "Discovery of Offer" http://www.w3.org/TR/web-payments-use-cases/
