### ISSUE TITLE
Meta-issue for sdo-enceladus release (likely as version 3.3)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1569]
Targeting for publication: May 2017 (as v3.3)

See http://webschemas.org/docs/releases.html#v3.3 for drafts in progress and associated release notes. 

Note that from version 3.2 onwards we are developing in the **master** branch here in Github, rather than using release-named branches. We keep the habit of code-naming releases, in case we change our mind about the specific version number to assign, but it is no longer also a Github branch.

Specifics:

* [ ] [Legislation extension](https://github.com/schemaorg/schemaorg/pull/1619) - merged to pending
 * merged, but needs final review and summary in releases.html (note: defines lots of inverse properties; natural final home would be a legal or civic -related hosted extension)
 * [ ] NewsArticle-related improvements #1525 (queued for review in http://webschemas.org/docs/releases.html#v3.3 )
  * strawman is in place, some points being discussed, examples could be extended.
 * [ ] HowTo structure, generalizing Recipe for non-food creations. Final drafting discussions in #1616
   * should be merged into Core but let's review the PR first
 * [x] EmployerReview #1576 1576
 * [x] to/cc/bccRecipient properties for EmailMessage #1590

**Comment by tfrancart** [comment]
External links in the release description (at http://webschemas.org/docs/releases.html#v3.3) ("European Legislation Identifier (ELI) ontology" and "ELI taskforce") don't work, they are interpreted as relative links). Sorry to be picky :-)

**Comment by danbri** [comment]
Thanks for catching that!

**Comment by danbri** [comment]
Note: @nicolastorzec made some useful comments on the NewsArticle-related vocabulary, in particular that that [SponsoredContentArticle](http://pending.webschemas.org/SponsoredContentArticle) type might need clarification w.r.t. when any CreativeWork with a sponsor counts under that more specific type.

**Comment by RichardWallis** [comment]
Following discussions, updating description for publicAccess to clarify usage.

**Comment by thadguidry** [comment]
@RichardWallis Thanks Richard, looks good.

**Comment by scor** [comment]
I'd be happy to review but wanted to check first if there is any work in progress to incorporate the feedback received so far.

**Comment by danbri** [comment]
Thanks @scor - you might look at #1525 and the discussion around NewsArticle, in particular @nicolastorzec and @tmarshbing 's comments. This is for changes that are mainly in the Pending section, so I'd argue that we can continue the conversation after actually publishing things into pending.schema.org proper for v3.3. I should be clear that at Google we are actively interested in using richer markup around news articles, and that we plan to explore implementation and report back on issues around markup usability (and if schema.org takes a different route after Pending, that's fine). The most fundamental discussion is around whether to use properties and multiple typing explicity in the markup or to simplify things by defining new types (which sometimes might have multiple supertypes), i.e. hardcoding possible common cases into schema.org.

**Comment by nicolastorzec** [comment]
@danbri, in the release note, the first link to issue 1525 is broken:
- it reads `https://github.com/schemaorg/schemaorg/issues1525c`
- but should be `https://github.com/schemaorg/schemaorg/issues/1525`

**Comment by sopekmir** [comment]
Dan, All, are there still chances to include in v3.3 our documentation for auto.schema.org:
https://github.com/schemaorg/schemaorg/issues/1677 ?
