### ISSUE TITLE
Meta-issue for upcoming release, drafted as v3.6 in master branch

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2193]
Tracking issue for upcoming 3.6 release

* Target release date: 2019-05-01 (Weds May 1st 2019)
* Target candidate release circulation date: 2019-04-15 (Monday April 15th 2019)

**Comment by danbri** [comment]
There are comments [from @philbarker](https://lists.w3.org/Archives/Public/public-schemaorg/2019Mar/0053.html) that may still need attention. 

* Q: Is the plan to move all the properties of Occupation from pending to 
core, or just the Class? (It looks like some but not all properties turn 
red)
  * A: yes, we did.
* Q: How do skills <https://webschemas.org/skills> relate to the common 
definition of competence (which centers on "knowledge, skills and 
abilities")? Dis-aggregating competences into constituent elements could 
be tricky.
  * A: to be discussed.
* If https://webschemas.org/experienceRequirements is "Description of 
skills and experience needed for the position or Occupation" do the 
skills go in two places?
  * to be discussed
* educationRequirements 
<https://pending.webschemas.org/educationRequirements> and 
qualifications <https://pending.webschemas.org/qualifications> seem very 
similar. I get the 'background' vs 'specific qualification' distinction, 
but are there many educationRequirements that wouldn't require some form 
of qualification as evidence?
  * A: to be discussed

/cc @vholland

**Comment by danbri** [comment]
Commited, needs release notes:

 * [x] https://github.com/schemaorg/schemaorg/pull/1975

**Comment by RichardWallis** [comment]
Candidate Pull Requests:
- [ ] #2203 Add Service to rangeIncludes of orderedItem
- [ ] #2204 Add LodgingBusiness to rangeIncludes of numberOfRooms
- [ ] #2174 Added number formatting advice to Number and relevant properties
- [ ] #2205 Add new property accessRights with domainIncludes CreativeWork
- [ ] #2082 Fix RDFa example for Website
- [ ] #2077 Fix JSON-LD example for availableLanguage
- [ ] #2207 Expanded rangeIncludes of occupationalCategory & jobTitle
- [ ] #2074 Clarifying relative sizes of region and locality in PostalAddress
- [ ] #2055 That's not what she said! 
- [ ] #2054 README correct two spelling mistakes
- [ ] #2036 Fix broken `url` term in `ItemList` example
- [ ] #2029 defining workload of a course instance
- [ ] #2013 Fix typo in hotels.html
- [ ] #2003 Improvements to descriptions of CampGround and CampingPitch
- [ ] #1989 isLiveBroadcast example: link instead of meta element
- [ ] #1937 Add a direct link to Developers page from Schemas page

**Comment by Tpt** [comment]
Two PRs adding what I think are missing `rdfs:subClassOf`:
- [ ] #1606 Makes Painting, Photograph and Sculpture subclasses of VisualArtwork
- [ ] #1607 Makes CatholicChurch subclass of Church

**Comment by RichardWallis** [comment]
I have added #1607 to the candidate list.  Plus a comment on #1606 that should be easy to review and update before then adding to the list.

~Richard.

**Comment by danbri** [comment]
maybe https://github.com/schemaorg/schemaorg/issues/2170 too

regarding DefinedTerm etc., it is a substantial sub-vocabulary, I'd like to see signs that it is being consumed somewhere.

**Comment by RichardWallis** [comment]
#1606 closed after discusion

**Comment by danbri** [comment]
Ok, I have made a pass through the issues above (thanks, @RichardWallis). Many are merged in (I've ticked them off inline in the Github comment). Some need more time and consideration. 

# Merged in for 3.6 release candidate review

#2203 Add Service to rangeIncludes of orderedItem
#2204 Add LodgingBusiness to domainIncludes of numberOfRooms
#2174 Added number formatting advice to Number and relevant properties
#2082 Fix RDFa example for Website
#2077 Fix JSON-LD example for availableLanguage
#2055 That's not what she said!
#2054 README correct two spelling mistakes
#2036 Fix broken url term in ItemList example
#2029 defining workload of a course instance
#2013 Fix typo in hotels.html
#2003 Improvements to descriptions of CampGround and CampingPitch
#1989 isLiveBroadcast example: link instead of meta element
#1937 Add a direct link to Developers page from Schemas page
#1607 Makes CatholicChurch subclass of Church
#1975 correcting format of durations, fixes #1470; correcting examples in timeRequired. Fixes #1469

# More work needed

#2205 Add new property accessRights with domainIncludes CreativeWork
 #2207 Expanded rangeIncludes of occupationalCategory & jobTitle
 #2074 Clarifying relative sizes of region and locality in PostalAddress
 #2170 Add named inverse for hasMenuItem

(and everything else)

**Comment by danbri** [comment]
For future releases, let's require every pullrequest to include text for docs/releases.html. This time around I'll do it, but it will help with keeping up momentum if that work can be distributed.

**Comment by danbri** [comment]
Created an issue for 3.7, https://github.com/schemaorg/schemaorg/issues/2239
