### ISSUE TITLE
Meta-issue for upcoming release, drafted as v3.7 in master branch 

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2239]
Tracking issue for upcoming release

* Target date: 2019-06-01 (officially Saturday June 1st 2019; freeze on Friday May 31st, publish Monday June 3rd)
* Circulate for review on or before: 2019-05-20 (Monday May 20th 2019)

**Comment by RichardWallis** [comment]
Candidate Pull Requests:
- [ ] #2207 Expanded rangeIncludes of occupationalCategory & jobTitle
- [ ] #2205 Add new property accessRights with domainIncludes CreativeWork
- [ ] #2074 Clarifying relative sizes of region and locality in PostalAddress
- [ ] #2170 Add named inverse for hasMenuItem
- [ ] #2168 Update issue-1698-examples.txt (fix broken JSON-LD)
- [ ] #2136 Fixing some typos and missing commas in Schedule Example 4 json-ld
- [ ] #2132 Adding some hierarchy to the documentation page
- [ ] #2041 Update accessModeSufficient to expect ItemList and correct first example
- [ ] #2028 isBasedOn definition and examples 
- [ ] #1991 releases.html: changed 3 links from 'webschemas.org' to 'schema.org'

**Comment by philbarker** [comment]
Maybe add 
- [ ] #2241 provides a status property for CreativeWork

**Comment by twamarc** [comment]
Hi @RichardWallis and @danbri: Please advise if we add the https://github.com/schemaorg/schemaorg/issues/2214 on this release? just to see if I need to prioritise the task.

**Comment by RichardWallis** [comment]
@twamarc You can create a PR for the fix whenever, then we can look to feeding into the next appropriate release.

**Comment by danbri** [comment]
also tweak for estimatedSalary values, #2251

**Comment by philbarker** [comment]
How about #2247 adding properties for when a job in a jobPosting starts?

**Comment by RichardWallis** [comment]
#2247 and #2254 (tweaks for estimatedSalary ) added to candidate list

**Comment by danbri** [comment]
"accessRights" (#2205) is a very thorny topic, I don't see any sign of sufficient consensus or data-consuming apps. #2241 deserves continuing discussion too...

I've circulated the following as a v3.7 release proposal:

#2207 Expanded rangeIncludes of occupationalCategory & jobTitle
#2170 Add named inverse for hasMenuItem
#2074 Clarifying relative sizes of region and locality in PostalAddress
#2168 Update issue-1698-examples.txt (fix broken JSON-LD)
#2136 Fixing some typos and missing commas in Schedule Example 4 json-ld
#2132 Adding some hierarchy to the documentation page
#2041 Update accessModeSufficient to expect ItemList and correct first example
#2028 isBasedOn definition and examples
#1991 releases.html: changed 3 links from 'webschemas.org' to 'schema.org'
#2254 Extend range of estimatedSalary to include MonetaryAmount and Number
#2247 adding properties to JobPosting to indicate when job starts

**Comment by vholland** [comment]
I commented on #2207. I think it is a mistake to remove occupationalCategory from JobPosting as that breaks existing markup on the web.

**Comment by danbri** [comment]
it should not be removed; if it has gone somehow, that is a bug

**Comment by danbri** [comment]
I've created #2272 for our next release, due out on Monday July 1st. This means we ought to be wrapping up a release candidate ASAP. There were a number of items from this issue which didn't get finalized in June's release, so let's start there...

**Comment by philbarker** [comment]
I've been meaning to ask why #2247 didn't make the june release? Hope it can be in for July
