### ISSUE TITLE
Meta-issue for upcoming release, drafted as v3.8 in master branch 

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2272]
Tracking issue for upcoming release
Target date: 2019-07-01 (Monday 1st July 2019)
Circulate for review on or before 2019-06-17

**Comment by RichardWallis** [comment]
Candidate Pull Requests:

- [ ] #2205 Add new property accessRights with domainIncludes CreativeWork
- [ ] #2170 Add named inverse for hasMenuItem
- [ ] #2041 Update accessModeSufficient to expect ItemList and correct first example
- [ ] #2247 adding properties to JobPosting to indicate when job starts
- [ ] #2241 provides a status property for CreativeWork
- [ ] #2267 Fixed typo in description of subjectOf 
- [ ] #2269 Removed unnecessary newlines from comments in CSV files.

**Comment by danbri** [comment]
In addition this release will contain:

* GTIN simplifications and modernization, as outlined in  https://github.com/schemaorg/schemaorg/issues/1244#issuecomment-466099422 
* Some more syntax bugfixes to our examples.

**Comment by danbri** [comment]
* Queued for review: https://webschemas.org/docs/releases.html
* Release draft email: https://lists.w3.org/Archives/Public/public-schemaorg/2019Jun/0016.html

**Comment by mkanzaki** [comment]
Is there any chance to proceed Archive related classes/properties to the Core? #1758 and #1759 were closed on adding them to the Pending, but it's not clear (for me) what criteria they should meet in order to advance.
Thanks.

**Comment by danbri** [comment]
@mkanzaki this was included in v3.5 recently, see https://schema.org/docs/releases.html#v3.5 https://schema.org/docs/releases.html#g1758 

I would encourage the view that these are now "in schema.org", and something that can and should be used (with care). We will make periodic reviews of Schema.org's Pending area to see which things are being used. If that use brings attention to problems or opportunities to improve the definitions, "Pending" makes it easier for us to change. We will try to make any changes respectful of existing deployments. If you know of use, please drop a note into the relevant github issue (even if it is closed).

**Comment by danbri** [comment]
released: https://schema.org/docs/releases.html#v3.8

**Comment by RichardWallis** [comment]
Shipped.
