### ISSUE TITLE
Meta-issue for upcoming release, drafted as v3.9 in master branch

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#2306]
Tracking issue for upcoming release
Target date: 2019-08-01 (Thursday 1st August 2019)
Circulate for review on or before 2019-07-18

**Comment by RichardWallis** [comment]
Candidate Pull Requests/Issues:

- [ ] #2300 Add a ratingExplanation property on Rating (and highlight factcheck / ClaimReview usecase)
- [ ] #2290 Add schema for educational programs
- [ ] #2295 Adding example for JobPosting
- [ ] #2292 Fix typos in Jane Doe’s name
- [ ] #2285 Further corrections to examples identified as errors by Travis CI scripts
- [ ] #2199 Grammar - remove extra yet  (from _knowsAbout_ description)

**Comment by danbri** [comment]
I've included tweaks to Edu Program schemas, and the recently circulated Population/Observation vocabulary too.
