### ISSUE TITLE
Version 6.0 planning (goal: 2019-12-01)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2376]
Planning issue for 6.0

- [ ] datasets-related topics:
    - [ ] Revisit/improve work around funding esp of datasets, #383 /cc @chrisgorgo
    - [ ] modelling acknowledgements eg. for datasets #2266  (postponed for post-6.0 --@danbri)

    - [x] Add a maintainer property per #2311 
    - [x] isPartOf / hasPart --- json-ld should expect a link not a string so add URL as a type #2321
    - [ ] ...
 - [x] https://github.com/schemaorg/schemaorg/issues/2381 clarify via rename that product return policy is merchant-level

- [x] https://github.com/schemaorg/schemaorg/issues/2397 - generalized datePosted
- [x] https://github.com/schemaorg/schemaorg/issues/637 - made offers and itemOffered true inverses

Candidate PRs for 6.0 release
- [x] #2367 Issue 2366 - Add example of Audiobook related to its printed counterpart
- [x] #2375 Updated descriptions for Offer and AggregateOffer re: default businessFunction value
- [ ] #2352 New Type - TextPronunciation
- [x] #2378 Added test to identify duplicate entries in jsonldcontext file
- [x] #2380 Add DateTime to range of datePublished
- [x] #2250 Rationalised enumeration definitions (including tests for valid definitions)
- [x] #2388 Fix errors in definition of eventSchedule property

**Comment by philbarker** [comment]
@danbri this month's contribution on JobPosting from TalentSignal group is PR #2385 Hopefully non-controversial.

**Comment by vholland** [comment]
I would like to add

- [ ] #2398 : Added isResizable to 3DModel
- [ ] #2399 : Added BroadcastService to the domain for inLanguage
- [ ] #2400 : Added SportsEvent to the domain for sport

**Comment by philbarker** [comment]
I think this is good to go too:
- [ ] #2402 : Information about employer in JobPosting

**Comment by danbri** [comment]
* fyi I'm a few days behind getting the 6.0 proposal out
* see also this from @ldodds - https://github.com/schemaorg/schemaorg/pull/2389#issuecomment-557550311

**Comment by WeaverStever** [comment]
PolicyPages seems non-controversial [#2350](https://github.com/schemaorg/schemaorg/issues/2350)

**Comment by vholland** [comment]
Is it too late to get in:
[ ] #2418: Add property for the types of financial aid available for an EducationalOccupationalProgram
[ ] #2419: Add properties to EducationalOccupationalProgram to model program duration and application dates
[ ] #2420: Extend the audio property's range to include MusicRecording
[ ] #2421: Extend the domain of interactionStatistic to include Person and Organization

**Comment by gmackenz** [comment]
May I humbly mention two candidates for 6.0 as well?

- [ ]  #2139 Create a new MediaGallery type

- [ ] #2405 A proposal for two new types: Guide & Recommendation

**Comment by danbri** [comment]
Running behind on this, but at least we know how 2020 will start! Thanks all...

**Comment by danbri** [comment]
@vholland what happened to isResizable? https://github.com/schemaorg/schemaorg/pull/2398

**Comment by danbri** [comment]
ok most of 6.0 is up at http://webschemas.org/docs/releases.html#v6.0 for review.

I still need to work on the datasets part (top of this page), plus improve the renaming of ProductReturn* to MerchantReturn* terms so that old descriptions point to newer.

**Comment by danbri** [comment]
Update: I propose we come back to 'Revisit/improve work around funding esp of datasets, #383 /cc @chrisgorgo' later in the month for v7. I have a little more work to do on dataset funding then I think we're ready to declare 6.0 release candidate.

**Comment by danbri** [comment]
I've been looking at the dataset (etc) funding piece (and whiteboard diagrams from discussion with @chrisgorgo). Since it is a complex pattern touching ~6 types I think it deserves writing up in a doc or dedicated issue for better sanity checking, including a properly worked example, so I'll postpone the implementation until next release.

**Comment by chrisgorgo** [comment]
Sounds ok to me, but pinging @natashafn for additional comments.
