### ISSUE TITLE
Version "8-ish" planning (goal: 2020-04-xx)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2528]
This issue records non-fasttracked additions that would normally be in a normal monthly release.

I suggest at least for the duration of COVID-19 lockdown period (when there is pressure to update quickly) we review non-urgent changes individually, so that they can be merged in whenever a release goes out, assuming no objections arise during our normal 10 business day review window.

# Additions to Pending for Steering Group review:

* [x] #2526 - add Hackathon type
  * Proposed for inclusion 2020-04-07 by @danbri; reviews invited from:
  * [ ] @tmarshbing 
  * [ ] @rvguha 
  * [ ] @scor 
  * [x] @vholland 
  * [ ] @nicolastorzec 
  * [ ] @tilid 
  * also [ ] @ldodds 
 * [x] #2427 (PR: #2428), LRMI updates to simply markup for commonly used relationships
    * Proposed for inclusion 2020-04-07 by @danbri (thanks @RichardWallis); reviews invited from:
    * [ ] @tmarshbing 
    * [ ] @rvguha 
    * [ ] @scor 
    * [x] @vholland 
    * [ ] @nicolastorzec 
    * [ ] @tilid
 * [x] #2384 (PR: #2492), eligibilityToWorkRequirement  property for JobPosting 
    * Proposed for inclusion 2020-04-07 by @danbri (thanks @RichardWallis); reviews invited from:
    * [ ] @tmarshbing 
    * [ ] @rvguha 
    * [ ] @scor 
    * [x] @vholland 
    * [ ] @nicolastorzec 
    * [ ] @tilid
* [x] #2545 - describing nonprofit status of organizations, Proposed for inclusion 2020-04-16 by @danbri 
    * [ ] @tmarshbing 
    * [ ] @rvguha 
    * [ ] @scor 
    * [ ] @vholland 
    * [ ] @nicolastorzec 
    * [ ] @tilid
* [x] #2506 - Pending vocabulary for online shipping details, Proposed for inclusion 2020-04-21 by @danbri 
    * [ ] @tmarshbing 
    * [ ] @rvguha 
    * [ ] @scor 
    * [ ] @vholland 
    * [ ] @nicolastorzec 
    * [ ] @tilid

**Comment by philbarker** [comment]
I'ld like to propose some updates from LRMI that simplify commonly used relationships, PR #2428 for issue #2427 

Also, a JobPosting property that wasn't quite ready from the previous update, PR #2492 which completes the enhancements identified in #2384

**Comment by danbri** [comment]
thanks @philbarker   - are those stable enough for review from today, or do they need any more attention first?

**Comment by philbarker** [comment]
@danbri they should be fully cooked and ready to go

**Comment by danbri** [comment]
Also please take a look https://github.com/schemaorg/schemaorg/pull/2545 - describing nonprofits

**Comment by danbri** [comment]
(/Hackathon was included in 7.04)

**Comment by danbri** [comment]
circulated: https://lists.w3.org/Archives/Public/public-schemaorg/2020Apr/0022.html
