### ISSUE TITLE
Create tracking issues for old proposals in W3C Wiki

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#265]
There are still proposals listed in https://www.w3.org/wiki/index.php?title=WebSchemas/SchemaDotOrgProposalsArchive#2011-2014_Proposals_for_Schema.org that are not tracked here or finalized. They should be noted in github issues.

**Comment by danbri** [comment]
These are unsorted and need issues.
- [ ] https://www.w3.org/wiki/WebSchemas/Sports
- [ ] https://www.w3.org/wiki/WebSchemas/PeriodicalsComics
- [ ] https://www.w3.org/wiki/WebSchemas/HistoricalDataSchema
- [ ] https://www.w3.org/wiki/WebSchemas/BioDatabases
- [ ] https://www.w3.org/wiki/WebSchemas/Breadcrumbs
- [ ] https://www.w3.org/wiki/WebSchemas/DiscussionSchema

**Comment by danbri** [comment]
Dissolution date was added - http://schema.org/dissolutionDate

**Comment by jpmckinney** [comment]
When was dissolutionDate added? It's not showing up in the [changelog](http://schema.org/docs/releases.html#v1.93). Just curious as I had [proposed](https://www.w3.org/wiki/WebSchemas/dissolutionDate) it.

**Comment by inetbiz** [comment]
@danbri :+1: I created Issue: schemaorg/schemaorg#542 to migrate **[DiscussionSchema]**(https://github.com/schemaorg/schemaorg/wiki/Discussion-Schema "Discussion Schema")

**Comment by danbri** [comment]
largely outdated, but some things recur... worth keeping around for reference
