### ISSUE TITLE
Version 12 Planning (goal: 2021-03-08)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2813]
Release notes and feedback page for v12

Release drafting URL: https://webschemas.org/docs/releases.html#v12

# Changes in Core section:
- [x] #2804 Add ineligibleRegion to MediaObject
- [x] #2821 Extend range of duration to Episode 
- [x] #1417 Fix typo in isLiveBroadcast description
- [x] #2786 Updated JSON-LD example for mainEntityOfPage
- [x] #2651 added BackOrder as an enumeration member of ItemAvailability 
* ...
# Changes in Pending section:
- [x] #2810 (bugfix) 
- [x] #2811 Structured product sizes
- [x] #2799 HealthAspectEnumeration
# Site
-  [x] #2836 Implementation of GitHub Actions based continuous integration tests
 - [x] #2822 Update breadcrumb punctuation on property pages
 - [x] https://github.com/schemaorg/schemaorg/pull/2789 Fix broken href links
 - [x] https://github.com/schemaorg/schemaorg/pull/2800 Tidy of directory structure
 - [x] https://github.com/schemaorg/schemaorg/pull/2814 Migrate vocabulary definition and canonical URIs to HTTPS
 - [x] https://github.com/schemaorg/schemaorg/pull/2815 Fix links to release pages
 - [x] https://github.com/schemaorg/schemaorg/issues/2805#issuecomment-762771176 404s

**Comment by danbri** [comment]
Aiming to release this around Feb 12, so circulate release draft Jan 27 to give 10 working days review

**Comment by danbri** [comment]
Also:

* https://github.com/schemaorg/schemaorg/pull/2804

**Comment by danbri** [comment]
Merged a quick fix: 

 * https://github.com/schemaorg/schemaorg/pull/2839

**Comment by danbri** [comment]
Updating release date goal to: 2021-03-08

**Comment by danbri** [comment]
clarifying schemaVersion property - https://github.com/schemaorg/schemaorg/pull/2840#pullrequestreview-593251328

**Comment by danbri** [comment]
This published - please report bugs here or on the list!
