### ISSUE TITLE
Version 13 Planning (goal: 2021-06-xx) 

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2884]
Release notes and feedback page for v13

Release drafting URL: https://webschemas.org/docs/releases.html#v13

(checkbox when release notes + edits are in the main branch)

- [x] bioschemas #2862 into Pending
  - [ ] address notes in https://github.com/schemaorg/schemaorg/pull/2863#pullrequestreview-665350232
- [x]  MediaReview improvements
- [x] Product return improvements #2880
- [x]  buyer / Org PR merged
- [x] directApply, #2907
- [x] #2899 actors on PodcastSeries
- [x] https://github.com/schemaorg/schemaorg/issues/991 - countryOf* - implemented but may need tweaks + mappings

non-vocab:

- [x] validator
- [x] developers page update for #2886

# Missing from previous releases 
- [x] #2911 -fix oversight in SeekToAction definition (@danbri mistake in prev release).
- [x] #2825 InteractionCounter needs startTime, endTime. A git commit got lost somehow.

## Postpone for v14 attention:

- [ ] suggest also https://github.com/schemaorg/schemaorg/issues/1516 (conformsTo)
- [ ] revisit itemReviewed / review #161
- [ ] #2841 (@stain suggestion) 
- [ ] usability roundup - need more suggestions! #2892

**Comment by danbri** [comment]
Non-Vocab:

 * https://github.com/schemaorg/schemaorg/issues/2886 from @stain

**Comment by danbri** [comment]
I want to collect a round of usability, cleanup and technical debt fixes before we push out a new release.

For example - https://github.com/schemaorg/schemaorg/issues/2892

Please suggest more!

**Comment by stain** [comment]
Would be good if #2841 was included so this schema.org release included a self-declaration of its own version beyond the NQ graph name (which URI does not resolve) – perhaps it can just use (a permalink redirecting to) https://schema.org/docs/releases.html#v13.0 for now to not require changes to how the distro is done?

**Comment by danbri** [comment]
Merged https://github.com/schemaorg/schemaorg/pull/2899 (actors/PodcastSeries)

TODO: add "Use pending for new vocab; direct changes to core are fine if only tweaking existing definitions" to howwework.html

**Comment by danbri** [comment]
I'm prepping for v13 release, just noticed that #2892 almost escaped attention; have made some edits around Blog and added to release notes. Although this is late in the review process I don't imagine anything I have done would be controversial.

**Comment by danbri** [comment]
v13 is published
