### ISSUE TITLE
Meta bug to provide overview of all python/site tool issues

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#3]
# 2020 Update

I've gone through these, closed a few, tagged others for move to the suggestions-questions-brainstorming repo.  I think we can close this issue (and maybe recycle it, as #3 is a good number).

# Original text

This issue was (originally) intended for high-level planning, and relates to the set of issues tagged as [site tools + python](https://github.com/schemaorg/schemaorg/issues?q=is%3Aopen+is%3Aissue+label%3A%22site+tools+%2B+python+code%22)

See #1 for overall plan, and #2 for vocabulary planning.

**Note:** 
- :arrow_forward: Being worked on
- :hand: Work paused
## Issues [to be] addressed
- Site HTML
  - [x] Issue (#67) RDFa in per term pages should include inverseOf & subPropertyOf
  - [x] Issue (#217) The rdfs:subClassOf links in RDFa markup have room for improvement
  - [x] Issue (#317) Add Turtle dumps on per-term views
  - [ ] Issue (#725) <Meta> Description tag to include term description of sensible length, breaking on a sentence boundary.  Issue extended to include same functionality for JSON-LD output also to strip out quotes and other breaking markup.
  - [ ] Issue (#1217) RDFa on Term page - subClassOf in odd place
- Example txt files
  - [ ] Issue (#54) Automate comparison of examples with Schema
  - [ ] Issue (#177) Every example should have a unique ID
  - [ ] Issue (#499) Generate a list of terms that do not appear in examples
  - [ ] Issue (#1104) Workflow needs syntax-checkers integrated for all examples
  - [ ] Issue (#1145) Clean up .txt files
- Tests
  - [x] Issue (#156) Test supercededBy & inverseOf don't point to same thing
  - [x] Issue (#250) Test ensuring sentences end on '.'
  - [x] Issue (#485) Testcase to catch case where a property points to an enum that we forgot to enumerate
  - [ ] Issue (#782) Add a scripts/ utility for QA of Web-served functionality
  - [x] Issue (#1205) Unit test warning if a property is inverseOf itself
  - [ ] Issue (#1280) Need python API telling us which examples exist in < 3 formats
  - [x] Issue (#1329) Test to catch terms that are subtype/property of an attic term
- Export formats / files
  - [x] Issue (#197) Always generate updated RDF, OWL, JSON-LD
  - [x] Issue (#208) Add more export formats
  - [x] Issue (#703) Content Negotiation for Turtle file
  - [x] Issue (#317 ) Add Turtle dumps on per-term views 
  - [x] Issue (#360) Representation of schema_org_rdfa in "canonized" Polyglot HTML5
  - [x] Issue (#390) CSV download of all terms
  - [x] Issue (#484) Release snapshot format improvements
  - [x] Issue (#1101) Should the version history of the schema.org JSONLD context file be archived.
- JSON-LD / Context
  - [x] Issue (#51) JSON-LD context problem for properties that can take both URL or Text
  - [x] Issue (#854) JSON-LD emerging best practice is to alias @type, @id (and other keywords)
  - [ ] Issue (#860) Add a 404 handler that detects lookupd of /id and /type (JSON-LD keywords) and explains what's up
- Language
  - [x] Issue (#491) Add the chinese translations
  - [x] Issue (#1282) data/*schema files should have consistent language tagging
- Meta vocabulary & display thereof
  - [x] Issue (#182) Add to RDFS Conventions for see-also-issue-tracker, or see-also-documentation link
  - [ ] Issues (#233) (#255) Add domainHint & rangeHints for properties
  - [x] Issue (#359) rdfs:comment ... Need quotation rules?
  - [x] Issue (#465) Document .py API + schema config markup for deprecating (rather than marking as supersededBy) terms
  - [ ] Issue (#914) Implement a mechanism for recording context-specific term definitions (textual at least)
  - [x] Issue (#1318) Create process/UI/etc for terms that graduate from Pending (or get archived/abandoned) - "attic"
- Site functionality
  - [x] Issue (#490) Site HTML should be responsive to people using tiny pocket computers
  - [x] Issue (#879) Collect some useful/interesting visualizations of the schema.org vocabularies
- Vocabulary Definition
  - [ ] Unit tests to check extension values
  - [ ] Extension vocabulary definition: 
    - [ ] Define overall state of extension - Proposed / Released
    - [ ] Define state of individual terms within released extension - Proposed / Accepted
    - [ ] Include release version

**Comment by danbri** [comment]
Fixed in https://github.com/schemaorg/schemaorg/issues/426, and followed up in #465

**Comment by danbri** [comment]
@RichardWallis ... are any of these closed but not indicated as done here?

**Comment by RichardWallis** [comment]
I think #208 should be closed.  Any remaining comments (eg. https) are covered elsewhere or probably not on the agenda for fixing now.  I believe closing this, with the 3.2 release, will draw a line under this area so that any remaining suggestions and/or concerns can be built from a clean foundation.

I have marked #1282 as done because @en tags have come out of bib files but I can't track down when it happened- so left the issue still open.
