### ISSUE TITLE
Version 14 Planning (goal: 2022-01-xx)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#3017]
- [ ] validator-related (add to navbar, document constraints, e.g.  around [contexts in json-ld](https://github.com/schemaorg/schemaorg/issues/2921#issuecomment-994882850)).
 - [x] Update supporting Python libraries - RDFLib 6.1, Python 3.10 PR#2990
 - [x] Add _provider_ property to _Action_ type #2927 
 - [x] Update datamodel.htm page - to indicate turtle is reference model form and to remove broken links #2965 
 - [x] Update webschemas wiki links in descriptions for accessibility properties #2985
 - [x] PR #3007 (products intended or suitable for adult audiences) - Expand _isFamilyFriendly_ domain to include _Product_ & _Offer_. Introduce _hasAdultConsideration_ property to _Product_ & _Offer_ and associated _AdultOrientedEnumeration_ enumeration with values: _AlcoholConsideration, ViolenceConsideration, HealthcareConsideration, NarcoticConsideration, TobaccoNicotineConsideration, SexualContentConsideration, WeaponConsideration, DangerousGoodConsideration, UnclassifiedAdultConsideration_.
 - [x] Support for ISO6523 organization identifiers #3008 - add _iso6523Code_ property to _Organization_ type.
 - [x] Support for country-specific return policies #3009 - add _applicableCountry_ property to _MerchantReturnPolicy_ type.
 - [x] Fix link to SOFTWARE_README on RAQ page. #3010
 - [x]  Add /CategoryCode to range of /category #3027 
 - [x] Add _OnlineBusiness_ as subtype of _Organization_ and _OnlineStore_ as subtype of _OnlineBusiness_  #3030

**Comment by tfrancart** [comment]
Maybe Merge #2698 ?

**Comment by alex-jansen** [comment]
V14 was released in March 2022 so closing this as completed.
