### ISSUE TITLE
Meta-issue: Provide guidance for proposing extensions and modifications via issue templates

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#3477]
Many users of schema.org end up in this repository because they find that the current state of the vocabulary does not fit their individual needs, e.g. missing properties, insufficient specificity, etc.

While feedback from users is essential for schema.org, such proposals often do not end up in actual extensions to the vocabulary, which creates frustration among the submitters and puts a workload on the schema.org core contributors.

It would be good to **create guidelines on (1) when and (2) how to propose changes or extensions to the vocabulary.**

This could be implemented as one or multiple [**Github issue templates**](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository); for inspiration, see e.g. this [collection of issue templates](https://github.com/stevemao/github-issue-templates), maybe accompanied by a dedicated page in the documentation.

Here are some first ideas (maybe a bit too specific; we must not discourage users from proposing changes, of course):

## Checklist

- [ ] My proposal is about the **vocabulary,** not about problems with existing tools (like validators), the consumption of data by search engines or other applications, or the underlying syntaxes like JSON-LD, Microdata, or RDFa.
- [ ] I have read the [guidelines on naming and styling](https://schema.org/docs/styleguide.html) in schema.org.
- [ ] I understand the basic conceptual model behind schema.org, namely the mechanism for domain and range.
- [ ] I am familiar with the [data types used in schema.org](https://schema.org/DataType)
- [ ] I checked the list of [existing types for values etc. (`schema:Intangible`)](https://schema.org/Intangible) and [`schema:Enumeration`](https://schema.org/Enumeration) insofar they are relevant for my proposal.
- [ ] I am familiar with the existing mechanisms for [qualitative values via `schema:QualitativeValue`](https://schema.org/QualitativeValue), [quantitative values via `schema:QuantitativeValue`](https://schema.org/QuantitativeValue), and [property-value pairs defined outside of schema.org via `schema:PropertyValue`](https://schema.org/PropertyValue) insofar they are relevant for my proposal.
- [ ] I have considered the usage of external standards or numbering schemes for my proposal, e.g. via [`schema:additionalType`](https://schema.org/additionalType) or [`schema:additionalProperty`](https://schema.org/additionalProperty).

## Content

- Which applications can be expected to consume the enhanced data? (Very often, proposing an extension included the implicit expectation that major search engines will also actually use it, which will depend on many factors and take time.)
- Can you provide URLs of Web pages that contain the respective information (e.g. that would benefit from the proposed extension)? Ideally, the URLs would be from different sites.
- Did you check if the required information could be modeled with existing schema.org types and properties, e.g. with minor modifications to the text of existing definitions or by adding types to the domain or range?

**Comment by mfhepp** [comment]
Some aspects are already addressed in the [README](https://github.com/schemaorg/schemaorg?tab=readme-ov-file#improving-schemas). Content from there could be reused or moved and replaced by a link.

**Comment by fthobe** [comment]
Hey @mfhepp Yes, I think I wrote that 3 times (twice in a discussion and made a ticket), I have not the feeling there's any appetite for more "structure" (pun intended), but if you would sponsor it I would write a .github file for the organization. Right now I have lost the faith that without support it would ever be implemented. I'd also love to write a great blog article about additions in 2025 (same lack here).

**Comment by fthobe** [comment]
@MatthiasWiesmann @rrlevering @alex-jansen would this have any success chance if I make a PR with Issue templates creating a .github/ISSUE_TEMPLATE folder?
