### ISSUE TITLE
Meta bug for sdo-gozer release - vocab issues

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#418]
Here is a rough pass through (currently half of) sdo-gozer vocabulary open issues. See also https://github.com/schemaorg/schemaorg/issues/417 from @vholland on possible major renamings.

https://github.com/schemaorg/schemaorg/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22sdo-gozer+release%22+label%3A%22schema.org+vocab%22

is:open is:issue milestone:"sdo-gozer release" label:"schema.org vocab"

Note that the lists below do not cover everything yet.

At this point we have ~26 open issues listed against Schema.org vocabulary for sdo-gozer release.

This started as @danbri 's run through of that list with suggested approach to each issue, but has been discussed and refined somewhat. It is still missing some non-gozer issue that were tagged as Q1 2015. Unless someone makes a persuasive case these will be pushed into Q2's rough milestone.

HANDLED

- [x] https://github.com/schemaorg/schemaorg/issues/366 Inconvenient change to schema:publication
      http://schema.org/publication "A publication event associated with the episode, clip or media object."
      Suggest "A publication event associated with the item."
- [x] https://github.com/schemaorg/schemaorg/issues/335 VideoGameSeries example on VideoGame uses gameLocation
    We have rough consensus:  add gameLocation to VideoGameSeries. Implemented therefore close, no need to track.
    Impl: https://github.com/schemaorg/schemaorg/commit/50958e2bd3c4fa20070bf03c3bc77a6df3aa31b6
- [x] https://github.com/schemaorg/schemaorg/issues/327 Add paymentUrl to Invoice
      Discussed with Vicki, she'll close it as "handled by PayAction", no change needed.
- [x] https://github.com/schemaorg/schemaorg/issues/316 warrantyPromise vs warranty - should they be converged to a single property?
       On BuyAction, SellAction: http://schema.org/warrantyPromise "The warranty promise(s) included in the offer." vs
       On Demand, Offer: http://schema.org/warranty (same text).
    Proposal: mark warranty as supersededBy warrantyPromise and have all domains included for both. Check with Martin Hepp.
- [x] https://github.com/schemaorg/schemaorg/issues/315 BroadcastService supertype should be Service, not Thing
    Proposal: do it.
- [x] https://github.com/schemaorg/schemaorg/issues/247 Actions vocab mis-use of 'antagonym', confirm then change to 'antonym'
    Proposal: Dan to double-check with Sam Goto then implement if confirmed.
- [x] https://github.com/schemaorg/schemaorg/issues/232 2.4 children? We say Number where we mean Integer
     Proposal: numAdults, numChildren, additionalNumberOfGuests should all take Integer not Number.
- [x] https://github.com/schemaorg/schemaorg/issues/225 Add a schemaVersion property
     Proposal: do it. Allow String or URL so others can deploy on their own vocabularies.
- [x] https://github.com/schemaorg/schemaorg/issues/213 eligibleRegion and ineligbleRegion have different associated types
     Proposal: do it. Done. I've merged pull request from MartinHepp.
- [x] https://github.com/schemaorg/schemaorg/issues/205 Description of headline property shows its newspaper heritage
    Proposal: Dan Scott suggests moving it to subtype and improving description. Postponing beyond sdo-gozer to give us time to check in with rNews team. So I'll mark it 'done' w.r.t. this gozer todo list.
- [x] https://github.com/schemaorg/schemaorg/issues/193 'review' and 'aggregateRating' omit Event
    Proposal: add "Event" as included in domain of these two properties.
- [x] https://github.com/schemaorg/schemaorg/issues/183 Add domainIncludes RsvpAction to comment property #183
    It has been suggested that RsvpAction descriptions would benefit from having ability to associate a comment.
    Proposal: do it. done. https://github.com/schemaorg/schemaorg/commit/d124ad9fd206a8089cacb2422debe6e9d0066df1
    Close! See also https://github.com/schemaorg/schemaorg/issues/300 not currently tagged for gozer re ReplyAction / answer.
- [x] https://github.com/schemaorg/schemaorg/issues/171 Remove Class from the domain of query on SearchAction. Proposal: do it. Cleanup of leftovers from an earlier design.
- [x] https://github.com/schemaorg/schemaorg/issues/140 Description of Rating is inadequate.
  Closing. This is fixed ("A rating is an evaluation on a numeric scale, such as 1 to 5 stars")

Under Discussion

- [x] https://github.com/schemaorg/schemaorg/issues/165 Ambiguous description of 'ingredients', 'recipeInstructions' in Recipe.    Proposal: take LjWatson's suggestions. Scor suggests renaming to singular form.

Postponed 

- [x] https://github.com/schemaorg/schemaorg/issues/161 itemReviewed inverseOf review
  Proposal: postpone. Not urgent or embarrassing.
- [x] https://github.com/schemaorg/schemaorg/issues/160 category should apply at least to Product, perhaps elsewhere.   Proposal: add domainIncludes for Product, Event, CreativeWork

Queued for Gozer Attention

- [ ] https://github.com/schemaorg/schemaorg/issues/417 Consider renaming generic types and properties
- [x] https://github.com/schemaorg/schemaorg/issues/365 'award' property also for Organization and Product?
- [ ] https://github.com/schemaorg/schemaorg/issues/139 Add mappings from music (proposal) to music ontology.
      proposal: worth trying for, but not essential to this release (and not a vocab issue really.). Volunteers?
- [ ] https://github.com/schemaorg/schemaorg/issues/131 Include schema:Product in range of schema:category #131.
      see also  #160 category should apply at least to Product, perhaps elsewhere. Proposal: add domainIncludes for Product, Event, CreativeWork
      currently listed for postponement.
- [x] https://github.com/schemaorg/schemaorg/issues/130 Check/Fix status of True and False. Proposal: Do it (guha's proposal)
- [ ] https://github.com/schemaorg/schemaorg/issues/112 downvoteCount, upvoteCount definitions should mention Comment type.
      Proposal: use 'item' language instead of question/answer.
- [ ] https://github.com/schemaorg/schemaorg/issues/109 "StructuredValue description is confusing ". Proposal: volunteers?
- [ ] https://github.com/schemaorg/schemaorg/issues/99 "Usability/quality issues with Offer (price, gtin, ...)".  Proposal: needs
   breaking out into sub-issues.
- [ ] https://github.com/schemaorg/schemaorg/issues/53 "Linter warnings on schema.org examples" proposal: Dan re-run gregg's tool, break out sub-issues.
- [ ] https://github.com/schemaorg/schemaorg/issues/8 "VOCAB: schema.org/box has the description for "polygon"". proposal: identify minimal fix, avoid big picture integrations.

Heavier Issues - Need research / analysis (we will postpone some...)

- [ ] "New property for location a CreativeWork was created/captured " https://github.com/schemaorg/schemaorg/issues/323 (was https://github.com/schemaorg/schemaorg/issues/249 contentLocation is ambiguous.)
- [ ] https://github.com/schemaorg/schemaorg/issues/333 BreadcrumbList: Clarify position and how it interacts with itemListOrder
- [ ] https://github.com/schemaorg/schemaorg/issues/239 thumbnail and thumbnailUrl seem synonyms.
     POSTPONE. Needs analysis, thumbnail may be used to point to inline bnode items.
- [ ] https://github.com/schemaorg/schemaorg/issues/233 schema:purpose is poorly defined
    NEEDS INVESTIGATION. Seems like a mess that should be cleaned. Volunteer?
- [ ] https://github.com/schemaorg/schemaorg/issues/218 Improve model for schema:DataType
     Postpone unless someone (guha) cares to investigate more deeply.
- [ ] https://github.com/schemaorg/schemaorg/issues/206 Clarify Rating e.g. itemReviewed should be applicable to Rating; make Rating a CreativeWork?  NEEDS REVIEW. I can't remember February already!
- [ ] https://github.com/schemaorg/schemaorg/issues/186  Meta bug for expressivity and syntax issues around opening/closing hours
     Postpone unless we have a volunteer asap.
- [ ] https://github.com/schemaorg/schemaorg/issues/176  Clarifying and formalizing PropertyValueSpecification to allow options
     Needs review. Volunteers? Postpone?
- [ ] https://github.com/schemaorg/schemaorg/issues/170 Clean up Comment vs UserComments vs CommentAction
     NEEDS REVIEW. We really ought to clean this up. Who can take a look?

**Comment by unor** [comment]
I assume https://github.com/schemaorg/schemaorg/issues/365 is relevant here, too? All agreed, the issue got closed, but there was no pull request attached. I made one after: https://github.com/schemaorg/schemaorg/pull/413

**Comment by danbri** [comment]
We are now down to 6 vocab issues against gozer, I think this one is now obsoleted by that progress.closing...
