### ISSUE TITLE
Meta bug for sdo-phobos release (as v2.2)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#827]
As of 2015-10-02 sdo-phobos is looking pretty complete. It is closed for substantive schema/example changes except those that arise here from final review by steering group. Let's aim to be done with this in a week or two.

/cc @pmika @mfhepp @ajax-als @scor @shankarnat @tmarshbing @tilid @vholland @rvguha 

See http://sdo-phobos.appspot.com/docs/releases.html for all substantial changes needing review.

## Known TODOs before we publish:

* [x] respond to #772 by updating about.html or adding a 'how we work' page.
* [x] add to FAQ: per #747 Clarify that we consider examples and /docs/* documentation to be under the same CC license as the other schemas (rather than licensed as the opensource software i.e. Apache2), and to contact us if this isn't enough. Add corresponding note to README.md in github repo.
* [x] add to FAQ: note that https:// should be considered acceptable in markup and that we expect in future / over time these will become default and canonical. But that http:// will continue to be fine too.
* [ ] (website infrastructure) add more IDs to examples, and more properties to TYPES: config so that examples show up there. (optional but good to do)
* [x] Blog post. Should cover last release and Extensions status too.
* [x] Update overview text for /docs/releases.html to summarize the release. Add a section on the status of the live extensions (bib, auto) and grouping recent changes to them.
 
## Possible additional changes

* actionPlatform's detailed enumerations (see #778) and openingHoursStatus (#824) proposals from @vholland who might care to argue for their inclusion. 

## Changes identified during review

* markup bug: https://github.com/schemaorg/schemaorg/issues/827#issuecomment-145141779  - thanks @mfhepp 
* discussion of hasOfferCatalog (thanks @mfhepp again), suggestion to [reuse makesOffer](https://github.com/schemaorg/schemaorg/pull/821#issuecomment-145047449) instead - seems to be consensus this is a good idea.

**Comment by danbri** [comment]
* ongoing review discussion includes https://github.com/schemaorg/schemaorg/pull/821 around OfferCatalog

**Comment by vholland** [comment]
There is also a discussion going on in Issue #818 re: OfferCatalog. Can people comment there so there are not any cross conversations?

/cc @pmika @mfhepp @ajax-als @scor @shankarnat @tmarshbing @tilid @danbri  @rvguha

**Comment by mfhepp** [comment]
As for  #810: postalCode and addressCountry are now an expected property for GeoShape and GeoCoordinates: I think "expected" is too strong. There are many relevant places like mountain summits that do not have a postal code.

**Comment by mfhepp** [comment]
On http://sdo-phobos.appspot.com/areaServed there are extra characters after "sub-properties":

ineligibleRegion. ''">eligibleRegion

**Comment by mfhepp** [comment]
As for #733 "Added example showing library availability for Book. Also added example for Library and linked it to openingHoursSpecification as a good example for that too."

1. The example does not show up for http://sdo-phobos.appspot.com/openingHoursSpecification.
2. The RDFa and Microdata examples for http://sdo-phobos.appspot.com/Library have very long lines. Limit the width of the examples to 65 or so characters.

**Comment by danbri** [comment]
@mfhepp - thanks re bug. And regarding 'expected', ah yes, I see that the word is ambiguous. We don't expect it always to be there, but if we see it, we are not surprised because "it isn't unexpected". Let's find a better phrase.

**Comment by mfhepp** [comment]
Besides these points made in here, I am fine with sdo-phobos as it stands - but I have a strong opion on the need for https://github.com/schemaorg/schemaorg/pull/828 ;-)

**Comment by mfhepp** [comment]
@danbri re "expected" - what about "allowed", "permitted", "supported" or "applicable" property ;-)?

**Comment by elf-pavlik** [comment]
http://sdo-phobos.appspot.com/memberOf
> An Organization (or ProgramMembership) to which this Person or Organization belongs.

could change to

*An Organization (or ProgramMembership) to which this Person belongs. Also valid for relating Organization with ProgramMembership, for relating Organizations with one another, please use [parentOrganization](http://schema.org/parentOrganization) and [subOrganization](http://schema.org/subOrganization)*

**Comment by RichardWallis** [comment]
"*for #733 "Added example showing library availability for Book*.":
* Added as example to openingHoursSpecification
* Long lines are now wrapped in example

Code updated - needs pushing to sdo-phobos /cc @danbri

**Comment by vholland** [comment]
I am trying to tie together the final details of OfferCatalog on issue #818. I would appreciate input there.

/cc @pmika @mfhepp @ajax-als @scor @shankarnat @tmarshbing @tilid @danbri @rvguha

**Comment by mfhepp** [comment]
As for signing off: I am fine with sdo-phobos as it stands, assuming that 
- OfferCatalog will be finalized as agreed in #818 (see there) and
- openingHoursStatus (#824) is not included without additional discussion because of potential conflicts
/cc @danbri

**Comment by shankarnat** [comment]
@danbri  For signing off, I agree with the proposal outlined #818 by @vholland and have responded on the thread. Please let know if there is anyother thread that needs attention. Thanks!

**Comment by danbri** [comment]
* I have just published some hopefully-final changes to #818 following discussion there - I believe we have reasonable consensus and a workable design. see http://sdo-phobos.appspot.com/OfferCatalog http://sdo-phobos.appspot.com/hasOfferCatalog (thanks @vholland for getting this wrapped up)
* Confirming that openingHoursStatus is not going into this release - needs more discussion. 
* @elf-pavlik I'm missing the context for memberOf tweak. We also have 'department'. Is there an associated issue, it seems worth investigating.
* I'm at W3C TPAC event currently, trying to review all comments on this release to make sure we didn't miss anything. It looks to me like we're pretty close, although there are some checklist items above that need attention still.

**Comment by vholland** [comment]
Yes, openingHoursStatus should be postponed to another release.

Vicki Tardif Holland | Ontologist | vtardif@google.com

**Comment by danbri** [comment]
I think we're done, except for blog post and about page and https://github.com/schemaorg/schemaorg/issues/445# needs another look w.r.t. adding an example for http://sdo-phobos.appspot.com/ExhibitionEvent

**Comment by danbri** [comment]
see also https://groups.google.com/forum/#!topic/schema-org-sg/or9tUyM7yqo and https://groups.google.com/forum/#!topic/schema-org-sg/s1km5-aYBQ8 ... I have circulated a (hopefully final) release candidate, http://sdo-phobos.appspot.com/docs/releases.html

I even more think that we are done now! Will throw together a quick blog post to match. PTAL.

**Comment by danbri** [comment]
Released 2015-11-05, thanks everyone! We packed a lot into this one, even if there were no "big headline" additions.

Blogged at http://blog.schema.org/2015/11/schemaorg-whats-new.html
