### ISSUE TITLE
Meta-issue for sdo-deimos release (eventually named as version 3.0)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#911]
This issue tracks release planning for schema.org's release codenamed sdo-deimos. ~~It is likely to be released as v2.3 in late 2015 or early 2016~~. It was [released as v3.0](http://schema.org/docs/releases.html#v3.0) in May 2016. 

# Early Access fixes

The following changes are proposed for immediate "early access" publication on the schema.org site. Such changes will be considered part of the eventual following release, for versioning/snapshot purposes. They will be published as soon as they get OK'd [by the schema.org steering group](https://groups.google.com/forum/#!topic/schema-org-sg/s8mGcSYh350). 

## Fix for 500 error codes - https://github.com/schemaorg/schemaorg/issues/899 - in #901 
SG signoffs:
- [x] Shankar/Tom/Steve
- [x] Charles/Alex
- [x] Peter
- [x] Martin
- [x] Stéphane
- [x] Vicki/Dan
  
## Fix for needless complex JSON-LD periodicals example - https://github.com/schemaorg/schemaorg/issues/904 in https://github.com/dbs/schemaorg/commit/8ecbfe027519286e0ee59f9f0fa51b7129e0ebe3

- [x] Shankar/Tom/Steve
- [x] Charles/Alex
- [x] Peter
- [x] Martin
- [x] Stéphane
- [x] Vicki/Dan

# Main content of release

(discussion invited, here or in [email](https://lists.w3.org/Archives/Public/public-schemaorg/) )

(checkmarks indicate a rough consensus design is implemented for final review)

Proposals for this release include: 

- [ ] Add hotels extension proposal #915 / https://github.com/schemaorg/schemaorg/pull/916
- [x] Add suitability to restricted diets to Recipe - https://github.com/schemaorg/schemaorg/issues/845 ( consider also #882 #458 #159). See [candidate release summary](https://github.com/schemaorg/schemaorg/issues/845#issuecomment-184710174) in #845 
- [ ] OpeningHours cleanup/clarification as outlined by @betehess - https://github.com/schemaorg/schemaorg/issues/245
- [x] Add more education/learning (lrmi) examples - see #912 fixes in #902 (todo: create a tracking issue)
- [ ] Finalize auto.schema.org (a pull-request is coming in the next days)
- [ ] Move auto.schema.org & bib.schema.org from 'pre-final preview release' state to a release state. (need a simple way to identify state in RDFa source files?)

**Comment by philbarker** [comment]
The examples for LRMI are ready, we'ld love to see them in the next release (see pull request #902 , sorry no issue raised)

**Comment by danbri** [comment]
LRMI examples would be great - let's do that

**Comment by vholland** [comment]
Would it be possible to also add the following:
* Add disambiguatingDescription to Thing (issue #880 and pull request #891)
* Adding mapDisplayOptions (issue #886 and pull request #892)
* Adding PreSale to availability (issue #888 and pull request #893)

**Comment by mfhepp** [comment]
I just added the hotel extension proposal #915 / #916. That would be a priority for me for the next release. Also, we should aim to finalize auto.schema.org (a pull-request is coming in the next days).

**Comment by RichardWallis** [comment]
Add moving the current auto & bib extensions from pre-final preview release to a released state.

**Comment by danbri** [comment]
(@mfhepp notes in IM chat that he has also checked off the 'early access fixes' above, which means we're good to go there)

**Comment by danbri** [comment]
OK it's time we started pulling this together as a release. Questions...

How ready are we with hotels? How close to some kind of consensus around dayOfWeek and opening hour improvements? What status updates for the bib.schema.org and auto.schema.org hosted extensions would be appropriate, and where/how shall we link the recently published GS1 external extension?

As a release http://sdo-deimos.appspot.com/docs/releases.html is quite slim. We should also collect up a few "low hanging fruit" bugfixes and simple improvements if there are any obvious quick-fix candidates.

/cc @scor @mfhepp @vholland @chaals @pmika @shankarnat @rvguha

**Comment by danbri** [comment]
Extensions

- [ ] auto: https://github.com/schemaorg/schemaorg/pull/922 I believe is latest from the Automotive group https://www.w3.org/community/gao/ @W3C-GAO main tracker is #704 - various small changes including removal of "This should be considered a pre-final preview release" language.
- [ ] bib: Also want to remove "This should be considered a pre-final preview release" as requested by @RichardWallis above. Also minor bugfix #984 needs reviewing and likely inclusion.
- [ ] health / medical: [recent update](https://github.com/schemaorg/schemaorg/issues/492#issuecomment-185090851) here: #492 from @twamarc - am trying to find best URL to review for the extension proposal.
- [ ] GS1's external extension (at http://gs1.org/voc/), see also [schema.org blog entry](http://blog.schema.org/2016/02/gs1-milestone-first-schemaorg-external.html). This needs to be linked from somewhere, as well as updates to docs/extension.html for the GS1 parts. I believe @mgh128 and @ekgs1 will supply new improved GS1 examples shortly, and that http://schema.org/docs/schemas.html is the best page for a featured "External Extensions' section.

**Comment by Dataliberate** [comment]
Scanning through the current set of PRs I believe the following are also good candidates for this release:

- [ ] (#924) ExternalEnumeration Proposal
- [ ] (#962) Expanding range and domain of sponsor property
- [ ] (#965) Financial (FIBO) proposals for core vocabulary 
- [ ] (#994)Composite pricing, updated
- [ ] (#998)Expanded sharedContent to coverage of SocialMediaPosting example

- [ ] (#1006) Expand Product properties onto Service

**Comment by unor** [comment]
I think two of my old PRs might be candidates for "quick fixes and easy wins", as they only fix example markup and got reviews:

* [ ] https://github.com/schemaorg/schemaorg/pull/836 "`PropertyValue` example fixes (pre-markup ex. had Microdata; `alt` attributes were missing)" 

* [ ] https://github.com/schemaorg/schemaorg/pull/910 "`ExhibitionEvent` example: fixes and cleanup"

I guess https://github.com/schemaorg/schemaorg/pull/909 ("`Review` example: use `reviewBody` instead of `description`") should be uncontroversial, too (would fix/close https://github.com/schemaorg/schemaorg/issues/881), but got no reviews.

**Comment by danbri** [comment]
Thanks @unor - those look useful, sorry we didn't get to them sooner!

**Comment by vholland** [comment]
Skimming through, I have a couple of (seemingly) uncontroversial pull requests that I would like to get in.
- [ ] #893 Added PreSale to ItemAvailability
- [ ] #880 Add disambiguatingDescription to Thing

**Comment by unor** [comment]
Some more easy/uncontroversial PRs:

* [ ] https://github.com/schemaorg/schemaorg/pull/947 (typo in `rdfs:label`/`rdfs:comment` of [`icaoCode`](http://schema.org/icaoCode))
* [ ] https://github.com/schemaorg/schemaorg/pull/954 (wrong spelling of `content` attributes in examples)
* [ ] https://github.com/schemaorg/schemaorg/pull/890 / https://github.com/schemaorg/schemaorg/pull/983 ([`containsPlace`](http://schema.org/containsPlace) currently links itself as inverse)

**Comment by wikier** [comment]
I wonder when could be the right time to properly discuss the event series and related features:

- [ ] #446 Add Event Series support 
- [ ] #445 Add ExhibitionEvent as a subtype of Event
- [ ] #910 ExhibitionEvent example: fixes and cleanup
- [ ] #916 Hotels Proposal Final

**Comment by danbri** [comment]
Event series may also be interesting wrt the Courses discussion nearby, where there is a need to distinguish the "course in the abstract" from a particular occurrence of it. The model feels a little different in that "lecture 5" in a sequence could occur eg 3 times in one year, but it is related somehow.

**Comment by philbarker** [comment]
+1 for Event Series as useful for Courses. 'Educational course is defined as "some sequence of events and/or creative works which aims to build the knowledge, competence or ability of learners".'

**Comment by danbri** [comment]
http://schema.org/workFeatured could help bridge educational events to
associated documentation eg curriculum / schedules

**Comment by wikier** [comment]
Ok @danbri, so since we didn't make it for sdo-gozer (v2.0), what aspects we should work out to get support for event series shipped into sdo-deimos (v2.3)?

**Comment by danbri** [comment]
@wikier re event series, could you take a look at the Courses discussions? They are currently struggling with the problem of describing a course in the abstract versus a course as a specific sequence of actual events. @philbarker probably has the best pointers but see [the mailing list](https://lists.w3.org/Archives/Public/public-schema-course-extend/) for one entry point.

**Comment by danbri** [comment]
I am working through the lists above. I would also like to fix #143 finally.

**Comment by danbri** [comment]
I've just #880 - added http://sdo-deimos.appspot.com/disambiguatingDescription - I think the Wikipedia usecase is compelling, but review welcomed.

**Comment by danbri** [comment]
http://webschemas.org/docs/releases.html is up to date with all changes in sdo-deimos repo.

Summarizing issues suggested in this thread...

# Fixed / merged / done

- [x] #893 Added PreSale to ItemAvailability - merged
- [x] #880 Add disambiguatingDescription to Thing - [added](http://webschemas.org/disambiguatingDescription) 
- [x] #890 / #983 (containsPlace currently links to itself as inverse) - merged
- [x] #947 (typo in rdfs:label/rdfs:comment of icaoCode) - merged
- [x] #954 (wrong spelling of content attributes in examples)
- [x] #445 Add ExhibitionEvent as a subtype of Event; already done but adding 'contributor' etc. as a property allowed on Event, see #1092
- [x] #910 ExhibitionEvent example: fixes and cleanup - merged

# For pending.schema.org on-ramp
- [x] #1061 Fact checking markup

# Still in progress

- [ ] #916 Hotels Proposal Final - @mfhepp is finalizing 
- [ ] #446 Add EventSeries support - working out details (in pending.schema.org currently); including supertype, definition.
- [ ] #923 Days of week and special/closing OpeningHoursSpecification
- [ ] #1092 Allow some existing people/org properties to apply to Event  (spinoff of #445, #503) 
- [ ] #143 Examples on openingHours should not use the 'time' element #143
- [ ] #492 Medical/health - moving a LOT of terms to health-lifesci. A first cut has been merged but we need QA and better status text on the extension homepage (draft health-lifesci.webschemas.org ) and also docs/medhealth.html updated. Also nearby a related (US insurance networks) health extension for pending.schema.org: #1062.

**Comment by danbri** [comment]
I have also just merged two piece of infrastructural work from @RichardWallis 

* https://github.com/schemaorg/schemaorg/pull/1075 - allows us to use markdown within comments for simpler crossreferencing [[Person]] instead of escaping lots of HTML code.
* https://github.com/schemaorg/schemaorg/pull/1074 - rdflib integration, which will allow us to read schemas in JSON-LD (when we choose to...)

Thanks @RichardWallis :)

**Comment by danbri** [comment]
http://webschemas.org/docs/releases.html  is now up to date with the repository so far. There are still some todos. Expecting FIBO and Hotels related pull requests from @RichardWallis and @mfhepp imminently. I am still doing QA on the gigantic medical changes, and I want to see what incremental progress we can mine from the various opening hours discussions. But do please take a look, we're nearly there...

**Comment by Dataliberate** [comment]
Issue #1059 <https://github.com/schemaorg/schemaorg/issues/1059>: Created
hosted extensions for ‘meta' vocabulary and for 'proposed' vocabulary under
review.

Shouldn’t that read ‘pending’ vocabulary under review.
——-

[core] Various typo fixes (including #1014
<https://github.com/schemaorg/schemaorg/pull/1014>.   - missing closing
bracket.

——

~Richard.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by danbri** [comment]
re #143 I saw @chaals yesterday and we agreed that switching from 'time' to 'span' made sense for non-standardized openingHours property values; that has been implemented.

**Comment by danbri** [comment]
Days of week / opening hours fixes are in. I'll circulate this for review as a release candidate.

**Comment by danbri** [comment]
Release candidate is for review. Thanks everyone for getting us this far :)

https://lists.w3.org/Archives/Public/public-schemaorg/2016Apr/0053.html

**Comment by danbri** [comment]
@trypuz notes that  "There is some error „404 Not Found” on http://webschemas.org/version/3.0/". This is true - the process for generating a full release is quite involved (see details at [https://github.com/schemaorg/schemaorg/blob/sdo-deimos/RELEASING.TXT](url)) so normally this happens only at final publication. I should make that more clear in the candidate release version of releases.html - thanks!

**Comment by chaals** [comment]
+1 for shipping.

**Comment by danbri** [comment]
Update w.r.t. releasing: we have +1s on shipping from @chaals @shankarnat @pmika @rvguha @danbri, waiting for @mfhepp and @scor (who thinks we may have some bugs left around opening hours).

**Comment by betehess** [comment]
As commented in https://github.com/schemaorg/schemaorg/pull/923#issuecomment-215526952, I think that `PublicHolidays` should not go in this release.

If the steering committee wants to go ahead, that's fine, I do want my comment to be a blocker.

**Comment by danbri** [comment]
Perhaps you meant to write "do not", @betehess?

**Comment by betehess** [comment]
@danbri yes, I realized my mistake right after clicking the "Comment" button. I actually wanted to emphasize the "do not" to make it clear, but my brain had a hiccup :-) I had already updated my comment in the GitHub UI.

I do think more thinking should go into `PublicHolidays`.

**Comment by danbri** [comment]
Re PublicHolidays I've filed #1139 but I'm coming at this from the view that we have already effectively had PublicHolidays for ~4 years. If we're going to add http://schema.org/Monday etc now we ought to provide a migration path for people using *all* the previous longer URLs for DayOfWeek. 

What I'd suggest (for after this release) is that it would be good to have some collaboration on a simple unit testing structure for openingHours information, to encourage interoperable implementation.

e.g. input to the test could be...

*  a set of triples representing information parsed [from Microdata](https://www.w3.org/TR/microdata-rdf/), JSON-LD or RDFa structured data
* a date/time in some ISO 8601 subset
* other contextual information e.g. a list of dates of public holidays for the appropriate locale

The output would be a boolean, whether the date/time is considered 'open' vs 'closed'.

**Comment by betehess** [comment]
I had not realized it was already there!  I agree with the rationale of keeping it.

Let's discuss about what to do with it in the next release.

**Comment by mfhepp** [comment]
Related resources (not necessarily up to date ;-):
- http://ebusiness-unibw.org/pipermail/goodrelations/2012-September/000475.html
- http://ebusiness-unibw.org/pipermail/goodrelations/2011-June/000369.html

Martin

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by danbri** [comment]
Ok via #1139 I think we're ok now with PublicHolidays for the release.

**Comment by danbri** [comment]
Ok release time. I'm about to work through the (rough) notes in https://github.com/schemaorg/schemaorg/blob/sdo-deimos/RELEASING.TXT ... essentially creating the derived per-release files that we snapshot. The DNS entries for new subdomains (pending.schema.org, health-lifesci.schema.org) should be mostly propagated already.

**Comment by danbri** [comment]
# v3.0 releasing

- [ ] releases.html updated with dated links and release description.
- [ ] scripts/run_tests.py no surprises.
- [ ] docs/qa.html all links healthy.
- [ ] any new DNS changes for extension subdomains have had 24h+ to propagate.
- [ ] sdoapp.py updated with matching SCHEMA_VERSION and releaselog entries.
- [ ] releases filetree static snapshot data:
 - [ ] mkdir data/releases/3.0/
 - [ ] cp data/schema.rdfa data/releases/3.0/
 - [ ] generate nquads/ntriples/turtle for core and for each extension, with #v3.0 in graph URI for the quads.
 - [ ] generate concatenated file from quads
- [ ] snapshot the per-release HTML summary page.
 - [ ] make sure all new files added to git repository.

**Comment by danbri** [comment]
Ok this is *mostly* published but we have an issue with AppEngine: the *new* subdomains for pending, meta and health-lifesci are not routing correctly to the appengine app. 

I will leave the new version published, despite this. It will mean a few people find links that don't yet work. I hope to get this fixed asap.

**Comment by danbri** [comment]
I've set things in motion for the subdomain URL mapping issue to be fixed (short version: we're using a special version of AppEngine with hidden complexities). This could take anything from 24h until early next week, so I have for now rolled back the site to the state of things on 2015-11-05. Apologies for the gracelessness! /cc @RichardWallis

**Comment by danbri** [comment]
Subdomain issue is fixed and the site is (largely) published, however there is also a problem with caching of old content - sometimes it is serving v2.2 version of pages (at least homepage and docs/schema.html). I have initiated a cache flush which might take 48h. Apologies for the clumsy release engineering...

See also https://lists.w3.org/Archives/Public/public-schemaorg/2016May/0042.html

**Comment by danbri** [comment]
Closing. https://github.com/schemaorg/schemaorg/issues/1212 is proposed for release as version 3.1, and should address the various glitches from 3.0.
